## ACIT 4880 - Lab 1 & 2 - Python Data Structures, Numpy, and Cell Magic

### Part 1 - Standard Data Structures

Q1. Create a nested tuple and print its first element

In [1]:
tuple = ((1,2),(3,4))
print(tuple[0][0])

1


Q2. Create a dictionary where
- You have a key name 'a' having an integer as its value, e.g., 'a': 42
- You have a key name 'b' having a list as its value, e.g., 'b': [2, 3, 4]
- Get the last list element with the key 'b', e.g., 4 from [2, 3, 4]

In [2]:
dic = {'a': 43, 'b': [2, 3, 4]}
print(dic['b'][len(dic['b']) - 1])

4


Q3. Add the key-value pair **'5': 'value'** to the dictionary

In [3]:
dic['5'] = 'value'

Q4. Print the dictionary, then delete the added element from the previous step, then print the dictionary again

In [4]:
print(dic)

{'a': 43, 'b': [2, 3, 4], '5': 'value'}


Q5. Update the existing dictionary, then print it again

In [5]:
dic.pop('5')
print(dic)

{'a': 43, 'b': [2, 3, 4]}


Q6. Explain (briefly) the output of the following code:

In [6]:
words = ['apple', 'bat', 'bar', 'atom', 'book']
by_letter = {}
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)
print(by_letter)

# iterates through words and gets the first letter of the word 
# if letter not in by_letter than add it with the key of letter and value of word
# else append the word to list

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}


Q7. What's interesting about the following output?

In [7]:
a = set([2, 2, 2, 1, 3, 3])
print(a)

#sets don't allow duplicates

{1, 2, 3}


Q8. Explain (briefly) each print output from the following code

In [8]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

c = a.union(b) #gets rid of same letters 
print(c)

d = a.intersection(b) # keeps only same letters
print(d)

a.add(6) # appends 6 to a 
print(a)

a.remove(6)# removes 6 to a, does nothing
print(a)

a.pop() #pop first element 
print(a)


{1, 2, 3, 4, 5, 6, 7, 8}
{3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5}
{2, 3, 4, 5}


## Part 2 - NumPy

Q1. Explain the results (i.e., the print statements) of the following code:

In [10]:
import numpy as np

x = np.array([1,1,2,2,3,5]) 
print(x)
print(x.shape) # prints the height width of matrix
y = x.reshape((2,3)) 
print(y)
print(y.shape) # prints the new height width of matrix, 2 rows by 3 columns



[1 1 2 2 3 5]
(6,)
[[1 1 2]
 [2 3 5]]
(2, 3)


Q2. Explain the results (i.e., the print statements) of the following code:

In [11]:
import numpy as np

a = np.arange(1, 20, 2) 
print(a) # evenly divides the numbers between 1-20 with 2 spaces

b = np.array([])
print(b) # array 

c = np.zeros(6)
print(c) # 6 zeros

d = np.ones(6)
print(d) # six 1s

e = np.array(range(1,6))
print(e) # array of numbers 1-6

np.linspace(0, 5, 50) #evenly spaced 50 numbers between 0 and 5

[ 1  3  5  7  9 11 13 15 17 19]
[]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1 2 3 4 5]


array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

Q3. Using Python for loop, find the indices of all values greater than 4 in the following array ***y***. 

y = [6, 10, 3, 4, 5, 6, 7]. 

In [12]:
for x in y:
    if x > 4:
        do smt

SyntaxError: invalid syntax (2959219462.py, line 3)

Q4. Explain the results (i.e., the print statements) of the following code:

In [13]:
y = np.array([6, 10, 3, 4, 5, 6, 7])
print(y.argmin()) #index of lowest val
i = np.where(y>4) #????????????????
print(i) 
y.sort()
x = y.copy()
print(x) # print sorted

2
(array([0, 1, 4, 5, 6], dtype=int64),)
[ 3  4  5  6  6  7 10]


Q5. Explain the results (i.e., the print statements) of the following code:

In [14]:
x = np.random.random_sample((3,3))
y = np.random.random_sample((3,3))

print(np.dot(x,y)) #product of two arrays x * y
print(np.cross(x,y)) # ^ cross
print(np.linalg.det(x)) #determinate ??
print(np.linalg.inv(x)) # multiplicative ??

[[0.54009843 0.74307291 0.29854779]
 [0.67174878 1.42308048 1.166365  ]
 [0.60669542 1.05852799 0.68693721]]
[[-0.12224636 -0.08187817  0.47650118]
 [ 0.59854818 -0.34606091  0.1899572 ]
 [-0.11104914  0.02913386  0.31375821]]
-0.10605453357071203
[[-0.02989903 -0.78213608  1.68051988]
 [-2.90927684 -0.16256418  2.97455993]
 [ 5.72754197  2.92126239 -7.2024833 ]]


Q6. Solve the following equations using ***numpy.linalg.solve()*** fundction:
- 5x + 2y = 3
- 6x - 5y = 4

In [15]:
print(np.linalg.solve([[5, 2],[6,-5]], [3,4]))

[ 0.62162162 -0.05405405]


Q7. Explain the results (i.e., the print statements)  of the following code:

In [16]:
data = np.random.randn(2,3)
print(data) # random array 2x3
print(data * 10) # 10x
print(data + data) # add to itself

[[-1.47483344  0.55244146  0.61810807]
 [ 0.82942281 -0.90989839  0.13661887]]
[[-14.74833443   5.52441463   6.18108069]
 [  8.29422813  -9.09898394   1.36618869]]
[[-2.94966689  1.10488293  1.23621614]
 [ 1.65884563 -1.81979679  0.27323774]]


Q8. Explain the results (i.e., the print statements) of the following code:

In [17]:
arr = np.arange(10) 
print(arr) # array 0-9
print(arr[5]) # first 5
print(arr[5:8]) # only 5-7

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


Q9. Explain each print statement (expect the print(break) statement) of the following code:

In [18]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
BREAK = ('*'*25)
print(names) # print names
print(BREAK)
print(data) # print random array 7x4
print(BREAK)
print(names == 'Bob') # true/false for each item in names true if bob
print(BREAK)
print(data[names == 'Bob', 2:]) # names is acting like the rows, so if true slice the first two (2:), print if element x in names == bob
print(BREAK)
print(data[names == 'Bob', 3]) # names is acting like the rows, so if true grab the 3rd, print if element x in names == bob
print(BREAK)
mask = (names == 'Bob') | (names == 'Will')
print(BREAK)
print(mask) # true if name is bob or will 
print(BREAK)
print(data[mask]) # print entire line if bob or will (row 1 3 4 5)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
*************************
[[-0.42771282  1.44506694  0.45379703  0.5235613 ]
 [ 0.32125807  1.25341914  0.0970015   0.46694981]
 [ 0.38469487 -1.14336344 -1.12783479 -0.40467829]
 [-0.02129214 -0.22156229 -0.38487859  1.12034402]
 [-0.88688876 -0.46114779 -1.09594718  1.08855686]
 [ 0.97418407  0.8473087  -1.20043741 -1.09366958]
 [ 0.06862254  0.85552688 -1.94295748  3.06009354]]
*************************
[ True False False  True False False False]
*************************
[[ 0.45379703  0.5235613 ]
 [-0.38487859  1.12034402]]
*************************
[0.5235613  1.12034402]
*************************
*************************
[ True False  True  True  True False False]
*************************
[[-0.42771282  1.44506694  0.45379703  0.5235613 ]
 [ 0.38469487 -1.14336344 -1.12783479 -0.40467829]
 [-0.02129214 -0.22156229 -0.38487859  1.12034402]
 [-0.88688876 -0.46114779 -1.09594718  1.08855686]]


Q10. Given the following matrix ***M1***:
- Print the 1st and 2nd row, and for columns, we want the first, second and third column, i.e., 
    - [[2 4 6]
    - [3 6 9]]
- Print all rows and third columns, i.e.,
    - [[ 6]
    - [ 9]
    - [12]
    - [15]]
- Print the first row and all columns, i.e.,
    - [[ 2  4  6  8 10]]
- Print the first three rows and first 2 columns, i.e.,
    - [[2 4]
    - [3 6]
    - [4 8]]

In [22]:
M1 = np.array ([[2, 4, 6, 8, 10],
               [3, 6, 9, -12, -15],
                [4, 8, 12, 16, -20],
                [5, -10, 15, -20, 25]])
print(M1[:2,:3])
print(M1[:len(M1),2])
print(M1[0])
print(M1[3:, :2])

[[2 4 6]
 [3 6 9]]
[ 6  9 12 15]
[ 2  4  6  8 10]
[[  5 -10]]


Q11. Create a numpy array and name it `weight_lb` (Give acceptable weight values for 10 humans)
- Multiply  by 0.453592 to go from pounds to kilograms and store the resulting numpy array as np_weight_kg
- Create np_height_m numpy array and store acceptable height values for 10 humans
- Calculate the BMI for each player using this equation:
    - BMI = weight(kg)/height(m) ** 2
- Save the resulting numpy array as BMI
- Print out BMI
- Create a boolean numpy array
    - The element of the array should be True if the corresponding baseball player's BMI is below 21
    - You can use the < operator for this
    - Name the array ***light*** and print it
- Print out a Numpy array with the BMIs of all baseball players whose BMI is below 21
    - Use ***light*** inside square brackets to do a selection on the BMI array
- Print the mean of np_height_m
- Print the median of np_height_m

In [23]:
import numpy as np

weight_lb = np.array([110, 130, 170, 180, 190, 200, 210, 220, 230, 240])

np_weight_kg = weight_lb * 0.453592

np_height_m = np.array([1.70, 1.75, 1.80, 1.85, 1.90, 1.75, 1.80, 1.85, 1.80, 1.75])

BMI = np_weight_kg / np_height_m ** 2

print("BMI:", BMI)

light = BMI < 21
print("Light players:", light)

print("BMI of light players:", BMI[light])

print("Mean height:", np.mean(np_height_m))
print("Median height:", np.median(np_height_m))


BMI: [17.2647474  19.25451755 23.79958025 23.85582469 23.87326316 29.62233469
 29.39948148 29.15711907 32.1994321  35.54680163]
Light players: [ True  True False False False False False False False False]
BMI of light players: [17.2647474  19.25451755]
Mean height: 1.7950000000000004
Median height: 1.8


## Part 3 - Magic command

Q1. Can you identify the performnace bottleneck of the following code using ***%%prun*** cell magic command?

In [40]:
import numpy as np

def matrix_multiply(A, B):
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])

    if cols_A != rows_B:
        raise ValueError("Incompatible matrix dimensions")

    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result


matrix_A = np.random.rand(1000, 50)
matrix_B = np.random.rand(50, 2000)


In [42]:
#You can use your cell profiler here

%prun result = matrix_multiply(matrix_A.tolist(), matrix_B.tolist())

In this example, the matrix_multiply function performs matrix multiplication using nested loops. However, this implementation can be inefficient for large matrices. The goal is to identify potential bottlenecks in the code and explore ways to optimize the matrix multiplication.

Q2. How to optimize the code above? Hint: Use NumPy for matrix multiplication.

- Can you identify the optimizated performance using %%prun cell magic?